linked account:  {u'referral_link': u'https://db.tt/aivRpNxF', u'display_name': u'Paul Chaignon', u'uid': 68977921, u'locale': u'en', u'email_verified': True, u'email': u'paul.chaignon@gmail.com', u'is_paired': False, u'team': None, u'name_details': {u'familiar_name': u'Paul', u'surname': u'Chaignon', u'given_name': u'Paul'}, u'country': u'FR', u'quota_info': {u'datastores': 0, u'shared': 0, u'quota': 56237228032, u'normal': 49006184205}}
uploaded:  {u'icon': u'page_white_picture', u'bytes': 260684, u'thumb_exists': True, u'rev': u'9361fb590', u'modified': u'Mon, 11 May 2015 19:56:31 +0000', u'client_mtime': u'Mon, 11 May 2015 19:56:31 +0000', u'path': u'/Screenshot.png', u'is_dir': False, u'size': u'254.6 KB', u'root': u'app_folder', u'mime_type': u'image/png', u'revision': 9}
paul@Omicron:~/github/Ayin$ 






paul@Omicron:~/github/Ayin$ python ayin.py 
linked account:  {u'referral_link': u'https://db.tt/aivRpNxF', u'display_name': u'Paul Chaignon', u'uid': 68977921, u'locale': u'en', u'email_verified': True, u'email': u'paul.chaignon@gmail.com', u'is_paired': False, u'team': None, u'name_details': {u'familiar_name': u'Paul', u'surname': u'Chaignon', u'given_name': u'Paul'}, u'country': u'FR', u'quota_info': {u'datastores': 0, u'shared': 0, u'quota': 56237228032, u'normal': 49006184205}}
Traceback (most recent call last):
  File "ayin.py", line 8, in <module>
    response = client.put_file('/Screenshot.png', f)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/client.py", line 377, in put_file
    return self.rest_client.PUT(url, file_obj, headers)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 321, in PUT
    return cls.IMPL.PUT(*n, **kw)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 258, in PUT
    return self.request("PUT", url, body=body, headers=headers, raw_response=raw_response)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 218, in request
    preload_content=False
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 579, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 579, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 579, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 265, in increment
    raise MaxRetryError(_pool, url, error)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-content.dropbox.com', port=443): Max retries exceeded with url: /1/files_put/auto/Screenshot.png?overwrite=False (Caused by ProtocolError('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution')))